nama=("Kartika Hastuti")
umur=int(("19"))
alamat=("lantan")
lulusan=("SARMA")
agama=("Islam")
nim=("SI20230020")
tgl=("17 Juli 2004")

print("=="*10)
print("|   NAMA      :", nama    )
print("|   NIM       :", nim     )
print("|   UMUR      :", umur    )
print("|   TGL LAHIR :", tgl    )
print("|   ALAMAT    :", alamat  )
print("|   AGAMA     :", agama   )
print("|   LULUSAN   :", lulusan )
print("=="*10)